"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asana_preview
from asana_preview.model.delete_attachment200_response import DeleteAttachment200Response


class TestDeleteAttachment200Response(unittest.TestCase):
    """DeleteAttachment200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteAttachment200Response(self):
        """Test DeleteAttachment200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteAttachment200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
