"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asana_preview
from asana_preview.model.remove_followers_request import RemoveFollowersRequest
globals()['RemoveFollowersRequest'] = RemoveFollowersRequest
from asana_preview.model.remove_followers_for_project_request import RemoveFollowersForProjectRequest


class TestRemoveFollowersForProjectRequest(unittest.TestCase):
    """RemoveFollowersForProjectRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoveFollowersForProjectRequest(self):
        """Test RemoveFollowersForProjectRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RemoveFollowersForProjectRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
