"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asana_preview
from asana_preview.model.task_response import TaskResponse
globals()['TaskResponse'] = TaskResponse
from asana_preview.model.create_task201_response import CreateTask201Response


class TestCreateTask201Response(unittest.TestCase):
    """CreateTask201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTask201Response(self):
        """Test CreateTask201Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTask201Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
