"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asana_preview
from asana_preview.model.task_count_response import TaskCountResponse
globals()['TaskCountResponse'] = TaskCountResponse
from asana_preview.model.get_task_counts_for_project200_response import GetTaskCountsForProject200Response


class TestGetTaskCountsForProject200Response(unittest.TestCase):
    """GetTaskCountsForProject200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTaskCountsForProject200Response(self):
        """Test GetTaskCountsForProject200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTaskCountsForProject200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
