"""
    Asana

    This is the interface for interacting with the Asana platform  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asana_preview
from asana_preview.model.get_events404_response_all_of_errors_inner import GetEvents404ResponseAllOfErrorsInner


class TestGetEvents404ResponseAllOfErrorsInner(unittest.TestCase):
    """GetEvents404ResponseAllOfErrorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEvents404ResponseAllOfErrorsInner(self):
        """Test GetEvents404ResponseAllOfErrorsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEvents404ResponseAllOfErrorsInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
