"""
    Asana

    This is the interface for interacting with the Asana platform  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asana_preview
from asana_preview.model.asana_named_resource_all_of import AsanaNamedResourceAllOf


class TestAsanaNamedResourceAllOf(unittest.TestCase):
    """AsanaNamedResourceAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAsanaNamedResourceAllOf(self):
        """Test AsanaNamedResourceAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AsanaNamedResourceAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
