"""
    Asana

    This is the interface for interacting with the Asana platform  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asana_preview
from asana_preview.model.get_events412_response_all_of_errors_inner import GetEvents412ResponseAllOfErrorsInner
globals()['GetEvents412ResponseAllOfErrorsInner'] = GetEvents412ResponseAllOfErrorsInner
from asana_preview.model.get_events412_response_all_of import GetEvents412ResponseAllOf


class TestGetEvents412ResponseAllOf(unittest.TestCase):
    """GetEvents412ResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEvents412ResponseAllOf(self):
        """Test GetEvents412ResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEvents412ResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
