"""
    Asana

    This is the interface for interacting with the Asana platform  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asana_preview
from asana_preview.model.error_response import ErrorResponse
from asana_preview.model.get_events401_response_all_of import GetEvents401ResponseAllOf
from asana_preview.model.get_events401_response_all_of_errors_inner import GetEvents401ResponseAllOfErrorsInner
globals()['ErrorResponse'] = ErrorResponse
globals()['GetEvents401ResponseAllOf'] = GetEvents401ResponseAllOf
globals()['GetEvents401ResponseAllOfErrorsInner'] = GetEvents401ResponseAllOfErrorsInner
from asana_preview.model.get_events401_response import GetEvents401Response


class TestGetEvents401Response(unittest.TestCase):
    """GetEvents401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEvents401Response(self):
        """Test GetEvents401Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEvents401Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
