"""
    Asana

    This is the interface for interacting with the Asana platform  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asana_preview
from asana_preview.model.task_base_all_of_external import TaskBaseAllOfExternal


class TestTaskBaseAllOfExternal(unittest.TestCase):
    """TaskBaseAllOfExternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskBaseAllOfExternal(self):
        """Test TaskBaseAllOfExternal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskBaseAllOfExternal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
