"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import asana_preview
from asana_preview.model.audit_log_event import AuditLogEvent
globals()['AuditLogEvent'] = AuditLogEvent
from asana_preview.model.get_audit_log_events200_response import GetAuditLogEvents200Response


class TestGetAuditLogEvents200Response(unittest.TestCase):
    """GetAuditLogEvents200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAuditLogEvents200Response(self):
        """Test GetAuditLogEvents200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAuditLogEvents200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
