# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/QDeviceLoadFrame_ui.ui',
# licensing of 'src/QDeviceLoadFrame_ui.ui' applies.
#
# Created: Tue Nov 16 20:28:53 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_deviceLoadFrame(object):
    def setupUi(self, deviceLoadFrame):
        deviceLoadFrame.setObjectName("deviceLoadFrame")
        deviceLoadFrame.resize(400, 544)
        deviceLoadFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        deviceLoadFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(deviceLoadFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.imageLabel = QtWidgets.QLabel(deviceLoadFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setMinimumSize(QtCore.QSize(128, 128))
        self.imageLabel.setMaximumSize(QtCore.QSize(128, 128))
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap(":/PNG/64/rfsource.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout_2.addWidget(self.imageLabel, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.onButton = QtWidgets.QPushButton(deviceLoadFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onButton.sizePolicy().hasHeightForWidth())
        self.onButton.setSizePolicy(sizePolicy)
        self.onButton.setMinimumSize(QtCore.QSize(64, 50))
        self.onButton.setMaximumSize(QtCore.QSize(64, 50))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.onButton.setFont(font)
        self.onButton.setAutoFillBackground(False)
        self.onButton.setStyleSheet("QPushButton#onButton {color: black; background-color: grey }")
        self.onButton.setFlat(False)
        self.onButton.setObjectName("onButton")
        self.horizontalLayout_2.addWidget(self.onButton)
        self.offButton = QtWidgets.QPushButton(deviceLoadFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offButton.sizePolicy().hasHeightForWidth())
        self.offButton.setSizePolicy(sizePolicy)
        self.offButton.setMinimumSize(QtCore.QSize(64, 50))
        self.offButton.setMaximumSize(QtCore.QSize(64, 50))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.offButton.setFont(font)
        self.offButton.setAutoFillBackground(False)
        self.offButton.setStyleSheet("QPushButton#offButton { color: white; background-color: red }")
        self.offButton.setFlat(False)
        self.offButton.setObjectName("offButton")
        self.horizontalLayout_2.addWidget(self.offButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.driverLabel = QtWidgets.QLabel(deviceLoadFrame)
        self.driverLabel.setObjectName("driverLabel")
        self.verticalLayout.addWidget(self.driverLabel)
        self.driverComboBox = QtWidgets.QComboBox(deviceLoadFrame)
        self.driverComboBox.setObjectName("driverComboBox")
        self.verticalLayout.addWidget(self.driverComboBox)
        self.addressTabWidget = QtWidgets.QTabWidget(deviceLoadFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addressTabWidget.sizePolicy().hasHeightForWidth())
        self.addressTabWidget.setSizePolicy(sizePolicy)
        self.addressTabWidget.setObjectName("addressTabWidget")
        self.addressTab = QtWidgets.QWidget()
        self.addressTab.setObjectName("addressTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.addressTab)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.addressTable = PropertyScrollArea(self.addressTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addressTable.sizePolicy().hasHeightForWidth())
        self.addressTable.setSizePolicy(sizePolicy)
        self.addressTable.setObjectName("addressTable")
        self.verticalLayout_10.addWidget(self.addressTable)
        self.addressTabWidget.addTab(self.addressTab, "")
        self.firmwareTab = QtWidgets.QWidget()
        self.firmwareTab.setObjectName("firmwareTab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.firmwareTab)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.firmwareTable = PropertyScrollArea(self.firmwareTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firmwareTable.sizePolicy().hasHeightForWidth())
        self.firmwareTable.setSizePolicy(sizePolicy)
        self.firmwareTable.setObjectName("firmwareTable")
        self.verticalLayout_11.addWidget(self.firmwareTable)
        self.addressTabWidget.addTab(self.firmwareTab, "")
        self.verticalLayout.addWidget(self.addressTabWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.testButton = QtWidgets.QPushButton(deviceLoadFrame)
        self.testButton.setObjectName("testButton")
        self.horizontalLayout_3.addWidget(self.testButton)
        self.loadDriverButton = QtWidgets.QPushButton(deviceLoadFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadDriverButton.sizePolicy().hasHeightForWidth())
        self.loadDriverButton.setSizePolicy(sizePolicy)
        self.loadDriverButton.setObjectName("loadDriverButton")
        self.horizontalLayout_3.addWidget(self.loadDriverButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.driverLabel.setBuddy(self.driverComboBox)

        self.retranslateUi(deviceLoadFrame)
        self.addressTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(deviceLoadFrame)
        deviceLoadFrame.setTabOrder(self.onButton, self.offButton)
        deviceLoadFrame.setTabOrder(self.offButton, self.driverComboBox)
        deviceLoadFrame.setTabOrder(self.driverComboBox, self.addressTabWidget)
        deviceLoadFrame.setTabOrder(self.addressTabWidget, self.testButton)
        deviceLoadFrame.setTabOrder(self.testButton, self.loadDriverButton)

    def retranslateUi(self, deviceLoadFrame):
        deviceLoadFrame.setWindowTitle(QtWidgets.QApplication.translate("deviceLoadFrame", "Frame", None, -1))
        self.onButton.setText(QtWidgets.QApplication.translate("deviceLoadFrame", "ON", None, -1))
        self.offButton.setText(QtWidgets.QApplication.translate("deviceLoadFrame", "OFF", None, -1))
        self.driverLabel.setText(QtWidgets.QApplication.translate("deviceLoadFrame", "Select Driver:", None, -1))
        self.addressTable.setToolTip(QtWidgets.QApplication.translate("deviceLoadFrame", "Property Browser", None, -1))
        self.addressTable.setWhatsThis(QtWidgets.QApplication.translate("deviceLoadFrame", "The Property Browser Controls Table Properties", None, -1))
        self.addressTabWidget.setTabText(self.addressTabWidget.indexOf(self.addressTab), QtWidgets.QApplication.translate("deviceLoadFrame", "Address", None, -1))
        self.firmwareTable.setToolTip(QtWidgets.QApplication.translate("deviceLoadFrame", "Property Browser", None, -1))
        self.firmwareTable.setWhatsThis(QtWidgets.QApplication.translate("deviceLoadFrame", "The Property Browser Controls Table Properties", None, -1))
        self.addressTabWidget.setTabText(self.addressTabWidget.indexOf(self.firmwareTab), QtWidgets.QApplication.translate("deviceLoadFrame", "Firmware", None, -1))
        self.testButton.setText(QtWidgets.QApplication.translate("deviceLoadFrame", "Test", None, -1))
        self.loadDriverButton.setText(QtWidgets.QApplication.translate("deviceLoadFrame", "Load", None, -1))

from sknrf.widget.propertybrowser.view.base import PropertyScrollArea
