# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'QSequencerView.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QToolBar,
    QWidget)

class Ui_sequencerMenu(object):
    def setupUi(self, sequencerMenu):
        if not sequencerMenu.objectName():
            sequencerMenu.setObjectName(u"sequencerMenu")
        sequencerMenu.resize(1388, 759)
        self.actionHelp = QAction(sequencerMenu)
        self.actionHelp.setObjectName(u"actionHelp")
        icon = QIcon()
        icon.addFile(u":/PNG/black/32/question_mark.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionHelp.setIcon(icon)
        self.actionLoad = QAction(sequencerMenu)
        self.actionLoad.setObjectName(u"actionLoad")
        icon1 = QIcon()
        icon1.addFile(u":/PNG/black/32/folder-open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLoad.setIcon(icon1)
        self.actionSave = QAction(sequencerMenu)
        self.actionSave.setObjectName(u"actionSave")
        icon2 = QIcon()
        icon2.addFile(u":/PNG/black/32/floppy-disk.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave_As = QAction(sequencerMenu)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionSave_As.setIcon(icon2)
        self.actionClose = QAction(sequencerMenu)
        self.actionClose.setObjectName(u"actionClose")
        self.actionNew = QAction(sequencerMenu)
        self.actionNew.setObjectName(u"actionNew")
        icon3 = QIcon()
        icon3.addFile(u":/PNG/black/32/document.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon3)
        self.actionStep = QAction(sequencerMenu)
        self.actionStep.setObjectName(u"actionStep")
        self.actionStep.setCheckable(True)
        icon4 = QIcon()
        icon4.addFile(u":/PNG/black/32/circled_next.png", QSize(), QIcon.Normal, QIcon.Off)
        icon4.addFile(u":/PNG/green/32/circled_next.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionStep.setIcon(icon4)
        self.actionStop = QAction(sequencerMenu)
        self.actionStop.setObjectName(u"actionStop")
        self.actionStop.setCheckable(True)
        icon5 = QIcon()
        icon5.addFile(u":/PNG/black/32/circled_stop.png", QSize(), QIcon.Normal, QIcon.Off)
        icon5.addFile(u":/PNG/red/32/circled_stop.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionStop.setIcon(icon5)
        self.actionRun = QAction(sequencerMenu)
        self.actionRun.setObjectName(u"actionRun")
        self.actionRun.setCheckable(True)
        icon6 = QIcon()
        icon6.addFile(u":/PNG/black/32/circled_border_triangle_right.png", QSize(), QIcon.Normal, QIcon.Off)
        icon6.addFile(u":/PNG/green/32/circled_border_triangle_right.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionRun.setIcon(icon6)
        self.actionCode = QAction(sequencerMenu)
        self.actionCode.setObjectName(u"actionCode")
        icon7 = QIcon()
        icon7.addFile(u":/PNG/black/32/circled_list.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCode.setIcon(icon7)
        self.actionCompile = QAction(sequencerMenu)
        self.actionCompile.setObjectName(u"actionCompile")
        icon8 = QIcon()
        icon8.addFile(u":/PNG/black/32/wrench.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCompile.setIcon(icon8)
        self.centralwidget = QWidget(sequencerMenu)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        sequencerMenu.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(sequencerMenu)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1388, 22))
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuBuild = QMenu(self.menubar)
        self.menuBuild.setObjectName(u"menuBuild")
        self.menuDebug = QMenu(self.menubar)
        self.menuDebug.setObjectName(u"menuDebug")
        sequencerMenu.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(sequencerMenu)
        self.statusbar.setObjectName(u"statusbar")
        sequencerMenu.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(sequencerMenu)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setEnabled(True)
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        sequencerMenu.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBuild.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuHelp.addAction(self.actionHelp)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuBuild.addAction(self.actionCode)
        self.menuBuild.addAction(self.actionCompile)
        self.menuDebug.addAction(self.actionStep)
        self.menuDebug.addAction(self.actionRun)
        self.menuDebug.addAction(self.actionStop)
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCode)
        self.toolBar.addAction(self.actionCompile)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStep)
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionStop)

        self.retranslateUi(sequencerMenu)

        QMetaObject.connectSlotsByName(sequencerMenu)
    # setupUi

    def retranslateUi(self, sequencerMenu):
        sequencerMenu.setWindowTitle(QCoreApplication.translate("sequencerMenu", u"Sequencer Menu", None))
        self.actionHelp.setText(QCoreApplication.translate("sequencerMenu", u"Help", None))
#if QT_CONFIG(tooltip)
        self.actionHelp.setToolTip(QCoreApplication.translate("sequencerMenu", u"Help", None))
#endif // QT_CONFIG(tooltip)
        self.actionLoad.setText(QCoreApplication.translate("sequencerMenu", u"Load", None))
        self.actionSave.setText(QCoreApplication.translate("sequencerMenu", u"Save", None))
        self.actionSave_As.setText(QCoreApplication.translate("sequencerMenu", u"Save As", None))
        self.actionClose.setText(QCoreApplication.translate("sequencerMenu", u"Close", None))
        self.actionNew.setText(QCoreApplication.translate("sequencerMenu", u"New", None))
        self.actionStep.setText(QCoreApplication.translate("sequencerMenu", u"Step", None))
#if QT_CONFIG(tooltip)
        self.actionStep.setToolTip(QCoreApplication.translate("sequencerMenu", u"Step", None))
#endif // QT_CONFIG(tooltip)
        self.actionStop.setText(QCoreApplication.translate("sequencerMenu", u"Stop", None))
#if QT_CONFIG(tooltip)
        self.actionStop.setToolTip(QCoreApplication.translate("sequencerMenu", u"Stop", None))
#endif // QT_CONFIG(tooltip)
        self.actionRun.setText(QCoreApplication.translate("sequencerMenu", u"Run", None))
#if QT_CONFIG(tooltip)
        self.actionRun.setToolTip(QCoreApplication.translate("sequencerMenu", u"Run", None))
#endif // QT_CONFIG(tooltip)
        self.actionCode.setText(QCoreApplication.translate("sequencerMenu", u"Code", None))
        self.actionCompile.setText(QCoreApplication.translate("sequencerMenu", u"Compile", None))
#if QT_CONFIG(tooltip)
        self.actionCompile.setToolTip(QCoreApplication.translate("sequencerMenu", u"Compile C Binary", None))
#endif // QT_CONFIG(tooltip)
        self.menuHelp.setTitle(QCoreApplication.translate("sequencerMenu", u"Help", None))
        self.menuFile.setTitle(QCoreApplication.translate("sequencerMenu", u"File", None))
        self.menuBuild.setTitle(QCoreApplication.translate("sequencerMenu", u"Build", None))
        self.menuDebug.setTitle(QCoreApplication.translate("sequencerMenu", u"Debug", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("sequencerMenu", u"toolBar", None))
    # retranslateUi

