# This file was auto-generated by Fern from our API Definition.

import typing

from .tax_status_dian import TaxStatusDian
from .tax_status_sat import TaxStatusSat

DetailTaxStatusResponse = typing.Union[TaxStatusSat, TaxStatusDian]
