from iparapheur_provisioning.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype_subtype_id_creation_permitted_desks.get import ApiForget


class ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdCreationPermittedDesks(
    ApiForget,
):
    pass
