
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-20T15:39:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7bacdf1dfb6d11579261fb032fc9ce49714b64af",
 "version": "0.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
