from .textagon import say_hello
from .textagon import ReadAllLexicons
from .textagon import SanityCheck
from .textagon import ReadRawText
from .textagon import setSpellChecking
from .textagon import TextToFeatures
from .textagon import TextToFeaturesReader
from .textagon import RunFeatureConstruction
from .textagon import ConstructLegomena
from .textagon import BuildFeatureVector
from .textagon import VectorProcessor
from .textagon import ResultWriter
from .textagon import runVader
from .textagon import GenerateColumnKey

from .textagon import HashLetters
from .textagon import ReadFeatures
from .textagon import ReadTrain
from .textagon import AssignTrainWeights
from .textagon import ReadSentiScores
from .textagon import ReadLex
from .textagon import NGramSemantic
from .textagon import AssignSemanticWeights
from .textagon import POSSemantic
from .textagon import POSWordSemantic
from .textagon import LEXSemantic
from .textagon import MatchCharSubstrings
from .textagon import MatchSubstrings
from .textagon import SubsumeCatN
from .textagon import SubsumeFeatures
from .textagon import RunSubsumptions
from .textagon import LoadHash
from .textagon import RunCCSubsumptions
from .textagon import RunParallels
from .textagon import ParallelCatN
from .textagon import ParaLex
from .textagon import Correlation
from .textagon import ParaPOS
from .textagon import OutputRankings
from .textagon import AFRN