# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QDataViewer.ui',
# licensing of 'QDataViewer.ui' applies.
#
# Created: Sat Jan 19 23:21:30 2019
#      by: pyside2-uic  running on PySide2 5.12.1a1
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_QDataViewer(object):
    def setupUi(self, QDataViewer):
        QDataViewer.setObjectName("QDataViewer")
        QDataViewer.resize(1304, 805)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QDataViewer.sizePolicy().hasHeightForWidth())
        QDataViewer.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(QDataViewer)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.sidebarFrame = QtWidgets.QFrame(self.splitter)
        self.sidebarFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sidebarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebarFrame.setObjectName("sidebarFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebarFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sidebarTabWidget = QtWidgets.QTabWidget(self.sidebarFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebarTabWidget.sizePolicy().hasHeightForWidth())
        self.sidebarTabWidget.setSizePolicy(sizePolicy)
        self.sidebarTabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.sidebarTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.sidebarTabWidget.setUsesScrollButtons(True)
        self.sidebarTabWidget.setDocumentMode(False)
        self.sidebarTabWidget.setObjectName("sidebarTabWidget")
        self.datagroupTab = QtWidgets.QWidget()
        self.datagroupTab.setObjectName("datagroupTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.datagroupTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.datagroupFrame = DatagroupFrame(self.datagroupTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datagroupFrame.sizePolicy().hasHeightForWidth())
        self.datagroupFrame.setSizePolicy(sizePolicy)
        self.datagroupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.datagroupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.datagroupFrame.setObjectName("datagroupFrame")
        self.verticalLayout_3.addWidget(self.datagroupFrame)
        self.sidebarTabWidget.addTab(self.datagroupTab, "")
        self.axesTab = QtWidgets.QWidget()
        self.axesTab.setObjectName("axesTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.axesTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.equationFrame = EquationFrame(self.axesTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equationFrame.sizePolicy().hasHeightForWidth())
        self.equationFrame.setSizePolicy(sizePolicy)
        self.equationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.equationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.equationFrame.setObjectName("equationFrame")
        self.verticalLayout_4.addWidget(self.equationFrame)
        self.sidebarTabWidget.addTab(self.axesTab, "")
        self.indexTab = QtWidgets.QWidget()
        self.indexTab.setObjectName("indexTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.indexTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.indexFrame = IndexFrame(self.indexTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indexFrame.sizePolicy().hasHeightForWidth())
        self.indexFrame.setSizePolicy(sizePolicy)
        self.indexFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.indexFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.indexFrame.setObjectName("indexFrame")
        self.verticalLayout_6.addWidget(self.indexFrame)
        self.sidebarTabWidget.addTab(self.indexTab, "")
        self.interpolationTab = QtWidgets.QWidget()
        self.interpolationTab.setObjectName("interpolationTab")
        self.sidebarTabWidget.addTab(self.interpolationTab, "")
        self.imagesTab = QtWidgets.QWidget()
        self.imagesTab.setObjectName("imagesTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.imagesTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.imageFrame = ImageFrame(self.imagesTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageFrame.sizePolicy().hasHeightForWidth())
        self.imageFrame.setSizePolicy(sizePolicy)
        self.imageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageFrame.setObjectName("imageFrame")
        self.verticalLayout_5.addWidget(self.imageFrame)
        self.sidebarTabWidget.addTab(self.imagesTab, "")
        self.verticalLayout_2.addWidget(self.sidebarTabWidget)
        self.contentFrame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentFrame.sizePolicy().hasHeightForWidth())
        self.contentFrame.setSizePolicy(sizePolicy)
        self.contentFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.contentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentFrame.setObjectName("contentFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.contentFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.contentTabWidget = QtWidgets.QTabWidget(self.contentFrame)
        self.contentTabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.contentTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.contentTabWidget.setUsesScrollButtons(True)
        self.contentTabWidget.setDocumentMode(False)
        self.contentTabWidget.setTabsClosable(True)
        self.contentTabWidget.setMovable(False)
        self.contentTabWidget.setObjectName("contentTabWidget")
        self.gridLayout.addWidget(self.contentTabWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        QDataViewer.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1304, 22))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        QDataViewer.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(QDataViewer)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        QDataViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(QDataViewer)
        self.statusBar.setObjectName("statusBar")
        QDataViewer.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(QDataViewer)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/black/32/cross-mark-on-a-black-circle-background.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(QDataViewer)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG/black/32/exclamation_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(QDataViewer)
        self.actionHelp.setCheckable(True)
        self.actionHelp.setChecked(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/PNG/black/32/question_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon2)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSave = QtGui.QAction(QDataViewer)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/PNG/black/32/floppy-disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtGui.QAction(QDataViewer)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/PNG/black/32/folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon4)
        self.actionLoad.setObjectName("actionLoad")
        self.actionUndo = QtGui.QAction(QDataViewer)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon5)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(QDataViewer)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon6)
        self.actionRedo.setObjectName("actionRedo")
        self.actionExport = QtGui.QAction(QDataViewer)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/PNG/black/32/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon7)
        self.actionExport.setObjectName("actionExport")
        self.actionSubplots = QtGui.QAction(QDataViewer)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/PNG/black/32/equalizer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSubplots.setIcon(icon8)
        self.actionSubplots.setObjectName("actionSubplots")
        self.actionSettings = QtGui.QAction(QDataViewer)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/PNG/black/32/cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon9)
        self.actionSettings.setObjectName("actionSettings")
        self.actionRefresh = QtGui.QAction(QDataViewer)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_sync.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon10)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionClear = QtGui.QAction(QDataViewer)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/PNG/black/32/cancel-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon11)
        self.actionClear.setObjectName("actionClear")
        self.actionNew = QtGui.QAction(QDataViewer)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/PNG/black/32/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon12)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionSubplots)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionRefresh)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClear)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExport)
        self.toolBar.addAction(self.actionSubplots)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addAction(self.actionClear)

        self.retranslateUi(QDataViewer)
        self.sidebarTabWidget.setCurrentIndex(2)
        self.contentTabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(QDataViewer)

    def retranslateUi(self, QDataViewer):
        QDataViewer.setWindowTitle(QtWidgets.QApplication.translate("QDataViewer", "DataViewer", None, -1))
        self.sidebarTabWidget.setTabText(self.sidebarTabWidget.indexOf(self.datagroupTab), QtWidgets.QApplication.translate("QDataViewer", "Datagroup", None, -1))
        self.sidebarTabWidget.setTabText(self.sidebarTabWidget.indexOf(self.axesTab), QtWidgets.QApplication.translate("QDataViewer", "Axes", None, -1))
        self.sidebarTabWidget.setTabText(self.sidebarTabWidget.indexOf(self.indexTab), QtWidgets.QApplication.translate("QDataViewer", "Index", None, -1))
        self.sidebarTabWidget.setTabText(self.sidebarTabWidget.indexOf(self.interpolationTab), QtWidgets.QApplication.translate("QDataViewer", "Interpolation", None, -1))
        self.sidebarTabWidget.setTabText(self.sidebarTabWidget.indexOf(self.imagesTab), QtWidgets.QApplication.translate("QDataViewer", "Images", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("QDataViewer", "File", None, -1))
        self.menuAbout.setTitle(QtWidgets.QApplication.translate("QDataViewer", "About", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("QDataViewer", "Edit", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("QDataViewer", "Exit", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("QDataViewer", "About", None, -1))
        self.actionHelp.setText(QtWidgets.QApplication.translate("QDataViewer", "Help", None, -1))
        self.actionHelp.setToolTip(QtWidgets.QApplication.translate("QDataViewer", "Help", None, -1))
        self.actionHelp.setShortcut(QtWidgets.QApplication.translate("QDataViewer", "Ctrl+/", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("QDataViewer", "Save", None, -1))
        self.actionSave.setToolTip(QtWidgets.QApplication.translate("QDataViewer", "Save Template", None, -1))
        self.actionSave.setShortcut(QtWidgets.QApplication.translate("QDataViewer", "Ctrl+S", None, -1))
        self.actionLoad.setText(QtWidgets.QApplication.translate("QDataViewer", "Load", None, -1))
        self.actionLoad.setToolTip(QtWidgets.QApplication.translate("QDataViewer", "Load Template", None, -1))
        self.actionLoad.setShortcut(QtWidgets.QApplication.translate("QDataViewer", "Ctrl+O", None, -1))
        self.actionUndo.setText(QtWidgets.QApplication.translate("QDataViewer", "Undo", None, -1))
        self.actionUndo.setShortcut(QtWidgets.QApplication.translate("QDataViewer", "Ctrl+Z", None, -1))
        self.actionRedo.setText(QtWidgets.QApplication.translate("QDataViewer", "Redo", None, -1))
        self.actionRedo.setToolTip(QtWidgets.QApplication.translate("QDataViewer", "Redo", None, -1))
        self.actionRedo.setShortcut(QtWidgets.QApplication.translate("QDataViewer", "Ctrl+Shift+Z", None, -1))
        self.actionExport.setText(QtWidgets.QApplication.translate("QDataViewer", "Export", None, -1))
        self.actionExport.setToolTip(QtWidgets.QApplication.translate("QDataViewer", "Export Figure", None, -1))
        self.actionExport.setShortcut(QtWidgets.QApplication.translate("QDataViewer", "Ctrl+P", None, -1))
        self.actionSubplots.setText(QtWidgets.QApplication.translate("QDataViewer", "Subplots", None, -1))
        self.actionSubplots.setToolTip(QtWidgets.QApplication.translate("QDataViewer", "Configure subplots", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("QDataViewer", "Settings", None, -1))
        self.actionSettings.setToolTip(QtWidgets.QApplication.translate("QDataViewer", "Settings", None, -1))
        self.actionSettings.setShortcut(QtWidgets.QApplication.translate("QDataViewer", "Ctrl+,", None, -1))
        self.actionRefresh.setText(QtWidgets.QApplication.translate("QDataViewer", "Refresh", None, -1))
        self.actionRefresh.setToolTip(QtWidgets.QApplication.translate("QDataViewer", "Redraw Figure", None, -1))
        self.actionRefresh.setShortcut(QtWidgets.QApplication.translate("QDataViewer", "Ctrl+R", None, -1))
        self.actionClear.setText(QtWidgets.QApplication.translate("QDataViewer", "Clear", None, -1))
        self.actionClear.setToolTip(QtWidgets.QApplication.translate("QDataViewer", "Clear Figure", None, -1))
        self.actionClear.setShortcut(QtWidgets.QApplication.translate("QDataViewer", "Ctrl+C", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("QDataViewer", "New", None, -1))
        self.actionNew.setToolTip(QtWidgets.QApplication.translate("QDataViewer", "New Figure", None, -1))
        self.actionNew.setShortcut(QtWidgets.QApplication.translate("QDataViewer", "Ctrl+N", None, -1))

from sknrf.app.dataviewer.view.filter.index import IndexFrame
from sknrf.app.dataviewer.view.datagroup.datagroup import DatagroupFrame
from sknrf.app.dataviewer.view.equation.equation import EquationFrame
from sknrf.app.dataviewer.view.image.image import ImageFrame
