# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTransformFrame_ui.ui',
# licensing of 'QTransformFrame_ui.ui' applies.
#
# Created: Mon Jan 14 10:22:27 2019
#      by: pyside2-uic  running on PySide2 5.12.1a1
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_transformFrame(object):
    def setupUi(self, transformFrame):
        transformFrame.setObjectName("transformFrame")
        transformFrame.resize(400, 300)
        transformFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        transformFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(transformFrame)
        self.verticalLayout.setSpacing(-1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(transformFrame)
        font = QtGui.QFont()
        #font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.calibrationLabel = QtWidgets.QLabel(transformFrame)
        font = QtGui.QFont()
        #font.setWeight(75)
        font.setBold(True)
        self.calibrationLabel.setFont(font)
        self.calibrationLabel.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.calibrationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.calibrationLabel.setObjectName("calibrationLabel")
        self.verticalLayout_2.addWidget(self.calibrationLabel)
        self.transformTable = QtWidgets.QTableWidget(transformFrame)
        self.transformTable.setObjectName("transformTable")
        self.transformTable.setColumnCount(0)
        self.transformTable.setRowCount(0)
        self.transformTable.horizontalHeader().setCascadingSectionResizes(False)
        self.transformTable.horizontalHeader().setSortIndicatorShown(False)
        self.transformTable.horizontalHeader().setStretchLastSection(True)
        self.transformTable.verticalHeader().setVisible(False)
        self.transformTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.transformTable)
        self.dutLabel = QtWidgets.QLabel(transformFrame)
        font = QtGui.QFont()
        #font.setWeight(75)
        font.setBold(True)
        self.dutLabel.setFont(font)
        self.dutLabel.setStyleSheet("background-color: rgb(0, 0, 0);\n" "color: rgb(255, 255, 255);")
        self.dutLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dutLabel.setObjectName("dutLabel")
        self.verticalLayout_2.addWidget(self.dutLabel)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(transformFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMinimumSize(QtCore.QSize(32, 32))
        self.addButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.removeButton = QtWidgets.QPushButton(transformFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setMinimumSize(QtCore.QSize(32, 32))
        self.removeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton.setIcon(icon1)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout.addWidget(self.removeButton)
        self.infoButton = QtWidgets.QPushButton(transformFrame)
        self.infoButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/PNG/black/32/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoButton.setIcon(icon2)
        self.infoButton.setObjectName("infoButton")
        self.horizontalLayout.addWidget(self.infoButton)
        self.upButton = QtWidgets.QPushButton(transformFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upButton.sizePolicy().hasHeightForWidth())
        self.upButton.setSizePolicy(sizePolicy)
        self.upButton.setMinimumSize(QtCore.QSize(32, 32))
        self.upButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_border_triangle_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon3)
        self.upButton.setObjectName("upButton")
        self.horizontalLayout.addWidget(self.upButton)
        self.downButton = QtWidgets.QPushButton(transformFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downButton.sizePolicy().hasHeightForWidth())
        self.downButton.setSizePolicy(sizePolicy)
        self.downButton.setMinimumSize(QtCore.QSize(32, 32))
        self.downButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_border_triangle_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon4)
        self.downButton.setObjectName("downButton")
        self.horizontalLayout.addWidget(self.downButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(transformFrame)
        QtCore.QMetaObject.connectSlotsByName(transformFrame)

    def retranslateUi(self, transformFrame):
        transformFrame.setWindowTitle(QtWidgets.QApplication.translate("transformFrame", "Frame", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("transformFrame", "Circuit Transforms:", None, -1))
        self.calibrationLabel.setText(QtWidgets.QApplication.translate("transformFrame", "Calibration Reference Plane", None, -1))
        self.dutLabel.setText(QtWidgets.QApplication.translate("transformFrame", "DUT Reference Plane", None, -1))
        self.addButton.setToolTip(QtWidgets.QApplication.translate("transformFrame", "Add", None, -1))
        self.removeButton.setToolTip(QtWidgets.QApplication.translate("transformFrame", "Remove", None, -1))
        self.infoButton.setToolTip(QtWidgets.QApplication.translate("transformFrame", "Info", None, -1))
        self.upButton.setToolTip(QtWidgets.QApplication.translate("transformFrame", "Shift Up", None, -1))
        self.downButton.setToolTip(QtWidgets.QApplication.translate("transformFrame", "Shift Down", None, -1))

