from .textagon import say_hello
from .textagon import ReadAllLexicons
from .textagon import SanityCheck
from .textagon import ReadRawText
from .textagon import setSpellChecking
from .textagon import TextToFeatures
from .textagon import TextToFeaturesReader
from .textagon import RunFeatureConstruction
from .textagon import ConstructLegomena
from .textagon import BuildFeatureVector
from .textagon import VectorProcessor
from .textagon import ResultWriter
from .textagon import runVader
from .textagon import GenerateColumnKey