# Generated by Django 3.2.18 on 2023-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialogue', '0002_auto_20230315_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
    ]
