# -*- coding: utf-8 -*-

"""
swaggerpetstore

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Action1Enum(object):

    """Implementation of the 'action1' enum.

    TODO: type enum description here.

    Attributes:
        VALIDATE: TODO: type description here.

    """

    VALIDATE = 'validate'
