# -*- coding: utf-8 -*-

"""
swaggerpetstore

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SortOrderEnum(object):

    """Implementation of the 'SortOrder' enum.

    Specifies an order sequence.

    Attributes:
        ASC: Sort result set by chosen field in ASCENDING order.
        DESC: Sort result set by chosen field in DESCENDING order.

    """

    ASC = 'ASC'

    DESC = 'DESC'
