from bpkio_cli.options.admin import extra_tenant_option as tenant
from bpkio_cli.options.json import json_options as json
from bpkio_cli.options.list import list_options as list
from bpkio_cli.options.poll import poll_options as poll
from bpkio_cli.options.read import read_options as read
from bpkio_cli.options.search import search_options as search
from bpkio_cli.options.search import validate_search_options as validate_search
from bpkio_cli.options.urls import url_options as url
from bpkio_cli.options.table import table_options as table
