# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QDatagroupFrame.ui',
# licensing of 'QDatagroupFrame.ui' applies.
#
# Created: Sat Jan 19 23:21:31 2019
#      by: pyside2-uic  running on PySide2 5.12.1a1
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_datagroupFrame(object):
    def setupUi(self, datagroupFrame):
        datagroupFrame.setObjectName("datagroupFrame")
        datagroupFrame.resize(398, 790)
        datagroupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        datagroupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout = QtWidgets.QGridLayout(datagroupFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.importLineEdit = QtWidgets.QLineEdit(datagroupFrame)
        self.importLineEdit.setEnabled(True)
        self.importLineEdit.setText("")
        self.importLineEdit.setObjectName("importLineEdit")
        self.gridLayout.addWidget(self.importLineEdit, 1, 0, 1, 1)
        self.importBrowseButton = QtWidgets.QPushButton(datagroupFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importBrowseButton.sizePolicy().hasHeightForWidth())
        self.importBrowseButton.setSizePolicy(sizePolicy)
        self.importBrowseButton.setObjectName("importBrowseButton")
        self.gridLayout.addWidget(self.importBrowseButton, 1, 1, 1, 1)
        self.datagroupLineEdit = QtWidgets.QLineEdit(datagroupFrame)
        self.datagroupLineEdit.setObjectName("datagroupLineEdit")
        self.gridLayout.addWidget(self.datagroupLineEdit, 2, 0, 1, 1)
        self.datagroupBrowseButton = QtWidgets.QPushButton(datagroupFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datagroupBrowseButton.sizePolicy().hasHeightForWidth())
        self.datagroupBrowseButton.setSizePolicy(sizePolicy)
        self.datagroupBrowseButton.setObjectName("datagroupBrowseButton")
        self.gridLayout.addWidget(self.datagroupBrowseButton, 2, 1, 1, 1)
        self.datagroupTreeView = DatagroupTreeView(datagroupFrame)
        self.datagroupTreeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.datagroupTreeView.setObjectName("datagroupTreeView")
        self.gridLayout.addWidget(self.datagroupTreeView, 3, 0, 1, 2)
        self.diffGroupBox = QtWidgets.QGroupBox(datagroupFrame)
        self.diffGroupBox.setEnabled(True)
        self.diffGroupBox.setObjectName("diffGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.diffGroupBox)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.absPushButton = QtWidgets.QPushButton(self.diffGroupBox)
        self.absPushButton.setEnabled(False)
        self.absPushButton.setObjectName("absPushButton")
        self.horizontalLayout.addWidget(self.absPushButton)
        self.relPushButton = QtWidgets.QPushButton(self.diffGroupBox)
        self.relPushButton.setEnabled(False)
        self.relPushButton.setObjectName("relPushButton")
        self.horizontalLayout.addWidget(self.relPushButton)
        self.ratioPushButton = QtWidgets.QPushButton(self.diffGroupBox)
        self.ratioPushButton.setEnabled(False)
        self.ratioPushButton.setObjectName("ratioPushButton")
        self.horizontalLayout.addWidget(self.ratioPushButton)
        self.customPushButton = QtWidgets.QPushButton(self.diffGroupBox)
        self.customPushButton.setEnabled(False)
        self.customPushButton.setObjectName("customPushButton")
        self.horizontalLayout.addWidget(self.customPushButton)
        self.gridLayout.addWidget(self.diffGroupBox, 4, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(datagroupFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 2)
        self.toolbarFrame = QtWidgets.QFrame(datagroupFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbarFrame.sizePolicy().hasHeightForWidth())
        self.toolbarFrame.setSizePolicy(sizePolicy)
        self.toolbarFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.toolbarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolbarFrame.setObjectName("toolbarFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.toolbarFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refreshToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_sync.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshToolButton.setIcon(icon)
        self.refreshToolButton.setIconSize(QtCore.QSize(24, 24))
        self.refreshToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.refreshToolButton.setAutoRaise(True)
        self.refreshToolButton.setObjectName("refreshToolButton")
        self.horizontalLayout_2.addWidget(self.refreshToolButton)
        self.line = QtWidgets.QFrame(self.toolbarFrame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.clearToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG/black/32/cancel-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearToolButton.setIcon(icon1)
        self.clearToolButton.setIconSize(QtCore.QSize(24, 24))
        self.clearToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.clearToolButton.setAutoRaise(True)
        self.clearToolButton.setObjectName("clearToolButton")
        self.horizontalLayout_2.addWidget(self.clearToolButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.toolbarFrame, 0, 0, 1, 2)

        self.retranslateUi(datagroupFrame)
        QtCore.QMetaObject.connectSlotsByName(datagroupFrame)
        datagroupFrame.setTabOrder(self.refreshToolButton, self.clearToolButton)
        datagroupFrame.setTabOrder(self.clearToolButton, self.importLineEdit)
        datagroupFrame.setTabOrder(self.importLineEdit, self.importBrowseButton)
        datagroupFrame.setTabOrder(self.importBrowseButton, self.datagroupLineEdit)
        datagroupFrame.setTabOrder(self.datagroupLineEdit, self.datagroupBrowseButton)
        datagroupFrame.setTabOrder(self.datagroupBrowseButton, self.datagroupTreeView)
        datagroupFrame.setTabOrder(self.datagroupTreeView, self.absPushButton)
        datagroupFrame.setTabOrder(self.absPushButton, self.relPushButton)
        datagroupFrame.setTabOrder(self.relPushButton, self.ratioPushButton)
        datagroupFrame.setTabOrder(self.ratioPushButton, self.customPushButton)

    def retranslateUi(self, datagroupFrame):
        datagroupFrame.setWindowTitle(QtWidgets.QApplication.translate("datagroupFrame", "Frame", None, -1))
        self.importLineEdit.setWhatsThis(QtWidgets.QApplication.translate("datagroupFrame", "<html><head/><body><p><br/></p></body></html>", None, -1))
        self.importLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("datagroupFrame", "Import Module Name", None, -1))
        self.importBrowseButton.setText(QtWidgets.QApplication.translate("datagroupFrame", "Browse", None, -1))
        self.datagroupLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("datagroupFrame", "Dataset Filename", None, -1))
        self.datagroupBrowseButton.setText(QtWidgets.QApplication.translate("datagroupFrame", "Browse", None, -1))
        self.diffGroupBox.setTitle(QtWidgets.QApplication.translate("datagroupFrame", "Diff:", None, -1))
        self.absPushButton.setText(QtWidgets.QApplication.translate("datagroupFrame", "Abs", None, -1))
        self.relPushButton.setText(QtWidgets.QApplication.translate("datagroupFrame", "Rel", None, -1))
        self.ratioPushButton.setText(QtWidgets.QApplication.translate("datagroupFrame", "Ratio", None, -1))
        self.customPushButton.setText(QtWidgets.QApplication.translate("datagroupFrame", "Custom", None, -1))
        self.refreshToolButton.setToolTip(QtWidgets.QApplication.translate("datagroupFrame", "Refresh", None, -1))
        self.refreshToolButton.setText(QtWidgets.QApplication.translate("datagroupFrame", "Refresh", None, -1))
        self.clearToolButton.setToolTip(QtWidgets.QApplication.translate("datagroupFrame", "Clear", None, -1))
        self.clearToolButton.setText(QtWidgets.QApplication.translate("datagroupFrame", "Clear", None, -1))

from sknrf.app.dataviewer.view.datagroup.widgets import DatagroupTreeView
