# Generated by Django 3.2 on 2023-05-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0002_drugdirectory_code_medu_cur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extragroup',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='base_system.hospital', verbose_name='所属医院'),
        ),
    ]
