# Generated by Django 3.2 on 2023-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0003_alter_extragroup_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extragroup',
            name='role_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='角色名称'),
        ),
    ]
