# Generated by Django 3.2 on 2023-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0006_alter_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extragroup',
            name='role_code',
            field=models.CharField(max_length=50, verbose_name='角色代码'),
        ),
        migrations.AlterUniqueTogether(
            name='extragroup',
            unique_together={('role_code', 'hospital')},
        ),
    ]
