BUYER_USER_TYPE = "B"
SELLER_USER_TYPE = "S"
FINANCIER_USER_TYPE = "F"
ALL_USER_TYPE = "A"

USER_TYPES = (
    (BUYER_USER_TYPE, "Buyer"),
    (SELLER_USER_TYPE, "Seller"),
    (FINANCIER_USER_TYPE, "Financier"),
    (ALL_USER_TYPE, "All"),
)

USER_TYPES_MAP = {
    BUYER_USER_TYPE: "Buyer",
    SELLER_USER_TYPE: "Seller",
    FINANCIER_USER_TYPE: "Financier",
    ALL_USER_TYPE: "All",
}

NEW_INVOICE_STATUS = "N"
VALIDATED_INVOICE_STATUS = "V"
COMPLETED_INVOICE_STATUS = "C"
CLOSED_INVOICE_STATUS = "X"
FUNDED_INVOICE_STATUS = "F"
REJECTED_INVOICE_STATUS = "R"
WITHDRAWN_INVOICE_STATUS = "W"
AMEND_INVOICE_STATUS = "A"

INVOICE_STATUSES = (
    (NEW_INVOICE_STATUS, "New"),
    (VALIDATED_INVOICE_STATUS, "Validated"),
    (COMPLETED_INVOICE_STATUS, "Completed"),
    (CLOSED_INVOICE_STATUS, "Closed"),
    (FUNDED_INVOICE_STATUS, "Funded"),
    (REJECTED_INVOICE_STATUS, "Rejected"),
    (WITHDRAWN_INVOICE_STATUS, "Withdrawn"),
    (AMEND_INVOICE_STATUS, "For Amendment"),
)

FAILED_TXN_STATUS = "F"
SUCCESS_TXN_STATUS = "S"
PENDING_TXN_STATUS = "P"
REVERSED_TXN_STATUS = "R"

TXN_STATUSES = (
    (FAILED_TXN_STATUS, "Failed"),
    (SUCCESS_TXN_STATUS, "Successful"),
    (PENDING_TXN_STATUS, "Pending"),
    (REVERSED_TXN_STATUS, "Reversed"),
)

FIXED_LIQUIFY_FEE = "F"
PERCENTAGE_LIQUIFY_FEE = "P"

LIQUIFY_FEE_TYPES = (
    (FIXED_LIQUIFY_FEE, "Fixed"),
    (FIXED_LIQUIFY_FEE, "Percentage"),
)

PENDING_CONTRACT_STATUS = "P"
ACCEPTED_CONTRACT_STATUS = "A"
MODIFY_CONTRACT_STATUS = "M"
VERIFIED_CONTRACT_STATUS = "V"
REJECTED_CONTRACT_STATUS = "R"
CONTRACT_STATUSES = (
    (PENDING_CONTRACT_STATUS, "Pending"),
    (ACCEPTED_CONTRACT_STATUS, "Accepted"),
    (MODIFY_CONTRACT_STATUS, "Modify"),
    (VERIFIED_CONTRACT_STATUS, "Verified"),
    (REJECTED_CONTRACT_STATUS, "Rejected"),
)
PHONE_CONTRACT_ACCEPTANCE = "P"
MAIL_CONTRACT_ACCEPTANCE = "M"
DASHBOARD_CONTRACT_ACCEPTANCE = "D"
CONTRACT_ACCEPTANCE_CHANNELS = (
    (PHONE_CONTRACT_ACCEPTANCE, "Phone"),
    (MAIL_CONTRACT_ACCEPTANCE, "Mail"),
    (DASHBOARD_CONTRACT_ACCEPTANCE, "Dashboard"),
)
