
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-17T16:27:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "504e084ee82af26c910ea1bf7bdf2b0ce7e4ed70",
 "version": "1.19.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
