
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7a3f4d38eedf783a56a0f63e673232954cd1dd3f",
 "version": "2.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
