# Generated by Django 3.2.18 on 2023-03-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='title slug'),
        ),
        migrations.AlterField(
            model_name='media',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='medialogue.album'),
        ),
        migrations.AlterField(
            model_name='media',
            name='date_taken',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date taken'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='slug'),
        ),
    ]
