
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-10T12:52:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ffc80356219e00f8b12e31bde091f14d8383234",
 "version": "1.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
