import typing_extensions

from iparapheur_provisioning.paths import PathValues
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_user_user_id import ApiProvisioningV1AdminUserUserId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id import ApiProvisioningV1AdminTenantTenantId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_user_user_id import ApiProvisioningV1AdminTenantTenantIdUserUserId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id import ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype_subtype_id import ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_desk_desk_id import ApiProvisioningV1AdminTenantTenantIdDeskDeskId
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant import ApiProvisioningV1AdminTenant
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_user import ApiProvisioningV1AdminTenantTenantIdUser
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type import ApiProvisioningV1AdminTenantTenantIdTypologyType
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype import ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtype
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_desk import ApiProvisioningV1AdminTenantTenantIdDesk
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_user import ApiProvisioningV1AdminUser
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology import ApiProvisioningV1AdminTenantTenantIdTypology
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype_subtype_id_metadata import ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdMetadata
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype_subtype_id_layer import ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdLayer
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype_subtype_id_filterable_by_desks import ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdFilterableByDesks
from iparapheur_provisioning.apis.paths.api_provisioning_v1_admin_tenant_tenant_id_typology_type_type_id_subtype_subtype_id_creation_permitted_desks import ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdCreationPermittedDesks

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.API_PROVISIONING_V1_ADMIN_USER_USER_ID: ApiProvisioningV1AdminUserUserId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID: ApiProvisioningV1AdminTenantTenantId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_USER_USER_ID: ApiProvisioningV1AdminTenantTenantIdUserUserId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_DESK_DESK_ID: ApiProvisioningV1AdminTenantTenantIdDeskDeskId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT: ApiProvisioningV1AdminTenant,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_USER: ApiProvisioningV1AdminTenantTenantIdUser,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE: ApiProvisioningV1AdminTenantTenantIdTypologyType,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtype,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_DESK: ApiProvisioningV1AdminTenantTenantIdDesk,
        PathValues.API_PROVISIONING_V1_ADMIN_USER: ApiProvisioningV1AdminUser,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY: ApiProvisioningV1AdminTenantTenantIdTypology,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID_METADATA: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdMetadata,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID_LAYER: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdLayer,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID_FILTERABLE_BY_DESKS: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdFilterableByDesks,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID_CREATION_PERMITTED_DESKS: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdCreationPermittedDesks,
    }
)

path_to_api = PathToApi(
    {
        PathValues.API_PROVISIONING_V1_ADMIN_USER_USER_ID: ApiProvisioningV1AdminUserUserId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID: ApiProvisioningV1AdminTenantTenantId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_USER_USER_ID: ApiProvisioningV1AdminTenantTenantIdUserUserId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_DESK_DESK_ID: ApiProvisioningV1AdminTenantTenantIdDeskDeskId,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT: ApiProvisioningV1AdminTenant,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_USER: ApiProvisioningV1AdminTenantTenantIdUser,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE: ApiProvisioningV1AdminTenantTenantIdTypologyType,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtype,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_DESK: ApiProvisioningV1AdminTenantTenantIdDesk,
        PathValues.API_PROVISIONING_V1_ADMIN_USER: ApiProvisioningV1AdminUser,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY: ApiProvisioningV1AdminTenantTenantIdTypology,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID_METADATA: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdMetadata,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID_LAYER: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdLayer,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID_FILTERABLE_BY_DESKS: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdFilterableByDesks,
        PathValues.API_PROVISIONING_V1_ADMIN_TENANT_TENANT_ID_TYPOLOGY_TYPE_TYPE_ID_SUBTYPE_SUBTYPE_ID_CREATION_PERMITTED_DESKS: ApiProvisioningV1AdminTenantTenantIdTypologyTypeTypeIdSubtypeSubtypeIdCreationPermittedDesks,
    }
)
