# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dylanbespalko/repos/scikit-nonlinear-core-dev/sknrf/view/desktop/dataviewer/equation/src/QDatasetEquationFrame.ui',
# licensing of '/Users/dylanbespalko/repos/scikit-nonlinear-core-dev/sknrf/view/desktop/dataviewer/equation/src/QDatasetEquationFrame.ui' applies.
#
# Created: Thu May 30 11:39:47 2019
#      by: pyside2-uic  running on PySide2 5.12.1a1
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_datasetEquationFrame(object):
    def setupUi(self, datasetEquationFrame):
        datasetEquationFrame.setObjectName("datasetEquationFrame")
        datasetEquationFrame.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(datasetEquationFrame.sizePolicy().hasHeightForWidth())
        datasetEquationFrame.setSizePolicy(sizePolicy)
        datasetEquationFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        datasetEquationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(datasetEquationFrame)
        self.verticalLayout.setSpacing(-1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.datasetLabel = QtWidgets.QLabel(datasetEquationFrame)
        font = QtGui.QFont()
        #font.setWeight(75)
        font.setBold(True)
        self.datasetLabel.setFont(font)
        self.datasetLabel.setObjectName("datasetLabel")
        self.verticalLayout.addWidget(self.datasetLabel)
        self.propertyTable = PropertyScrollArea(datasetEquationFrame)
        self.propertyTable.setObjectName("propertyTable")
        self.verticalLayout.addWidget(self.propertyTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(datasetEquationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMinimumSize(QtCore.QSize(32, 32))
        self.addButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.removeButton = QtWidgets.QPushButton(datasetEquationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setMinimumSize(QtCore.QSize(32, 32))
        self.removeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton.setIcon(icon1)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout.addWidget(self.removeButton)
        self.infoButton = QtWidgets.QPushButton(datasetEquationFrame)
        self.infoButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/PNG/black/32/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoButton.setIcon(icon2)
        self.infoButton.setObjectName("infoButton")
        self.horizontalLayout.addWidget(self.infoButton)
        self.upButton = QtWidgets.QPushButton(datasetEquationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upButton.sizePolicy().hasHeightForWidth())
        self.upButton.setSizePolicy(sizePolicy)
        self.upButton.setMinimumSize(QtCore.QSize(32, 32))
        self.upButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_border_triangle_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon3)
        self.upButton.setObjectName("upButton")
        self.horizontalLayout.addWidget(self.upButton)
        self.downButton = QtWidgets.QPushButton(datasetEquationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downButton.sizePolicy().hasHeightForWidth())
        self.downButton.setSizePolicy(sizePolicy)
        self.downButton.setMinimumSize(QtCore.QSize(32, 32))
        self.downButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/PNG/black/32/circled_border_triangle_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon4)
        self.downButton.setObjectName("downButton")
        self.horizontalLayout.addWidget(self.downButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(datasetEquationFrame)
        QtCore.QMetaObject.connectSlotsByName(datasetEquationFrame)

    def retranslateUi(self, datasetEquationFrame):
        datasetEquationFrame.setWindowTitle(QtWidgets.QApplication.translate("datasetEquationFrame", "Frame", None, -1))
        self.datasetLabel.setText(QtWidgets.QApplication.translate("datasetEquationFrame", "Dataset Equations:", None, -1))
        self.propertyTable.setToolTip(QtWidgets.QApplication.translate("datasetEquationFrame", "Property Browser", None, -1))
        self.propertyTable.setWhatsThis(QtWidgets.QApplication.translate("datasetEquationFrame", "The Property Browser Controls Table Properties", None, -1))

from sknrf.widget.propertybrowser.view.base import PropertyScrollArea
from sknrf.icons import black_32_rc
