# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QEquationFrame.ui',
# licensing of 'QEquationFrame.ui' applies.
#
# Created: Sat Jan 19 23:21:31 2019
#      by: pyside2-uic  running on PySide2 5.12.1a1
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_equationFrame(object):
    def setupUi(self, equationFrame):
        equationFrame.setObjectName("equationFrame")
        equationFrame.resize(496, 798)
        equationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        equationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout = QtWidgets.QGridLayout(equationFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.selectAxesLabel = QtWidgets.QLabel(equationFrame)
        self.selectAxesLabel.setObjectName("selectAxesLabel")
        self.gridLayout.addWidget(self.selectAxesLabel, 1, 0, 1, 1)
        self.axesTitleLineEdit = QtWidgets.QLineEdit(equationFrame)
        self.axesTitleLineEdit.setObjectName("axesTitleLineEdit")
        self.gridLayout.addWidget(self.axesTitleLineEdit, 3, 1, 1, 7)
        self.titleLabel = QtWidgets.QLabel(equationFrame)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 3, 0, 1, 1)
        self.selectedAxesComboBox = QtWidgets.QComboBox(equationFrame)
        self.selectedAxesComboBox.setObjectName("selectedAxesComboBox")
        self.selectedAxesComboBox.addItem("")
        self.gridLayout.addWidget(self.selectedAxesComboBox, 1, 1, 1, 7)
        self.axesTitleLabel = QtWidgets.QLabel(equationFrame)
        self.axesTitleLabel.setObjectName("axesTitleLabel")
        self.gridLayout.addWidget(self.axesTitleLabel, 2, 0, 1, 1)
        self.axesComboBox = QtWidgets.QComboBox(equationFrame)
        self.axesComboBox.setObjectName("axesComboBox")
        self.axesComboBox.addItem("")
        self.axesComboBox.addItem("")
        self.axesComboBox.addItem("")
        self.gridLayout.addWidget(self.axesComboBox, 2, 1, 1, 7)
        self.majorGridCheckBox = QtWidgets.QCheckBox(equationFrame)
        self.majorGridCheckBox.setChecked(True)
        self.majorGridCheckBox.setObjectName("majorGridCheckBox")
        self.gridLayout.addWidget(self.majorGridCheckBox, 4, 1, 1, 1)
        self.minorGridCheckBox = QtWidgets.QCheckBox(equationFrame)
        self.minorGridCheckBox.setChecked(True)
        self.minorGridCheckBox.setObjectName("minorGridCheckBox")
        self.gridLayout.addWidget(self.minorGridCheckBox, 4, 4, 1, 2)
        self.gridLabel = QtWidgets.QLabel(equationFrame)
        self.gridLabel.setObjectName("gridLabel")
        self.gridLayout.addWidget(self.gridLabel, 4, 0, 1, 1)
        self.selectedPlotComboBox = QtWidgets.QComboBox(equationFrame)
        self.selectedPlotComboBox.setObjectName("selectedPlotComboBox")
        self.gridLayout.addWidget(self.selectedPlotComboBox, 11, 1, 1, 7)
        self.selectedPlotLabel = QtWidgets.QLabel(equationFrame)
        self.selectedPlotLabel.setObjectName("selectedPlotLabel")
        self.gridLayout.addWidget(self.selectedPlotLabel, 11, 0, 1, 1)
        self.plotLabel = QtWidgets.QLabel(equationFrame)
        self.plotLabel.setObjectName("plotLabel")
        self.gridLayout.addWidget(self.plotLabel, 12, 0, 1, 1)
        self.xStrLabel = QtWidgets.QLabel(equationFrame)
        self.xStrLabel.setObjectName("xStrLabel")
        self.gridLayout.addWidget(self.xStrLabel, 13, 0, 1, 1)
        self.xStrLineEdit = QtWidgets.QLineEdit(equationFrame)
        self.xStrLineEdit.setObjectName("xStrLineEdit")
        self.gridLayout.addWidget(self.xStrLineEdit, 13, 1, 1, 6)
        self.yTableView = EquationTableView(equationFrame)
        self.yTableView.setStyleSheet("QTableView { selection-background-color: palette(Highlight); }")
        self.yTableView.setAlternatingRowColors(True)
        self.yTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.yTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.yTableView.setObjectName("yTableView")
        self.yTableView.horizontalHeader().setStretchLastSection(True)
        self.yTableView.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.yTableView, 10, 3, 1, 5)
        self.plotComboBox = QtWidgets.QComboBox(equationFrame)
        self.plotComboBox.setObjectName("plotComboBox")
        self.gridLayout.addWidget(self.plotComboBox, 12, 1, 1, 7)
        self.xFormatComboBox = QtWidgets.QComboBox(equationFrame)
        self.xFormatComboBox.setObjectName("xFormatComboBox")
        self.xFormatComboBox.addItem("")
        self.xFormatComboBox.addItem("")
        self.xFormatComboBox.addItem("")
        self.xFormatComboBox.addItem("")
        self.xFormatComboBox.addItem("")
        self.xFormatComboBox.addItem("")
        self.xFormatComboBox.addItem("")
        self.gridLayout.addWidget(self.xFormatComboBox, 13, 7, 1, 1)
        self.yFormatComboBox = QtWidgets.QComboBox(equationFrame)
        self.yFormatComboBox.setObjectName("yFormatComboBox")
        self.yFormatComboBox.addItem("")
        self.yFormatComboBox.addItem("")
        self.yFormatComboBox.addItem("")
        self.yFormatComboBox.addItem("")
        self.yFormatComboBox.addItem("")
        self.yFormatComboBox.addItem("")
        self.yFormatComboBox.addItem("")
        self.gridLayout.addWidget(self.yFormatComboBox, 14, 7, 1, 1)
        self.yStrLabel = QtWidgets.QLabel(equationFrame)
        self.yStrLabel.setObjectName("yStrLabel")
        self.gridLayout.addWidget(self.yStrLabel, 14, 0, 1, 1)
        self.yStrLineEdit = QtWidgets.QLineEdit(equationFrame)
        self.yStrLineEdit.setObjectName("yStrLineEdit")
        self.gridLayout.addWidget(self.yStrLineEdit, 14, 1, 1, 6)
        self.lineStyleLabel = QtWidgets.QLabel(equationFrame)
        self.lineStyleLabel.setObjectName("lineStyleLabel")
        self.gridLayout.addWidget(self.lineStyleLabel, 15, 1, 1, 1)
        self.lineCheckBox = QtWidgets.QCheckBox(equationFrame)
        self.lineCheckBox.setObjectName("lineCheckBox")
        self.gridLayout.addWidget(self.lineCheckBox, 15, 0, 1, 1)
        self.lineSizeSpinBox = QtWidgets.QSpinBox(equationFrame)
        self.lineSizeSpinBox.setMinimum(1)
        self.lineSizeSpinBox.setProperty("value", 2)
        self.lineSizeSpinBox.setObjectName("lineSizeSpinBox")
        self.gridLayout.addWidget(self.lineSizeSpinBox, 15, 6, 1, 2)
        self.lineSizeLabel = QtWidgets.QLabel(equationFrame)
        self.lineSizeLabel.setObjectName("lineSizeLabel")
        self.gridLayout.addWidget(self.lineSizeLabel, 15, 5, 1, 1)
        self.markerCheckBox = QtWidgets.QCheckBox(equationFrame)
        self.markerCheckBox.setChecked(True)
        self.markerCheckBox.setObjectName("markerCheckBox")
        self.gridLayout.addWidget(self.markerCheckBox, 16, 0, 1, 1)
        self.markerSizeLabel = QtWidgets.QLabel(equationFrame)
        self.markerSizeLabel.setObjectName("markerSizeLabel")
        self.gridLayout.addWidget(self.markerSizeLabel, 16, 5, 1, 1)
        self.markerStyleLabel = QtWidgets.QLabel(equationFrame)
        self.markerStyleLabel.setObjectName("markerStyleLabel")
        self.gridLayout.addWidget(self.markerStyleLabel, 16, 1, 1, 1)
        self.optionsLineEdit = QtWidgets.QLineEdit(equationFrame)
        self.optionsLineEdit.setObjectName("optionsLineEdit")
        self.gridLayout.addWidget(self.optionsLineEdit, 17, 1, 1, 7)
        self.optionsLabel = QtWidgets.QLabel(equationFrame)
        self.optionsLabel.setObjectName("optionsLabel")
        self.gridLayout.addWidget(self.optionsLabel, 17, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(equationFrame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 18, 0, 1, 8)
        self.plotPushButton = QtWidgets.QCommandLinkButton(equationFrame)
        self.plotPushButton.setObjectName("plotPushButton")
        self.gridLayout.addWidget(self.plotPushButton, 19, 0, 1, 8)
        self.transformLabel = QtWidgets.QLabel(equationFrame)
        self.transformLabel.setObjectName("transformLabel")
        self.gridLayout.addWidget(self.transformLabel, 8, 0, 1, 1)
        self.line = QtWidgets.QFrame(equationFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 0, 1, 8)
        self.transformComboBox = QtWidgets.QComboBox(equationFrame)
        self.transformComboBox.setObjectName("transformComboBox")
        self.gridLayout.addWidget(self.transformComboBox, 8, 1, 1, 7)
        self.xEquationLabel = QtWidgets.QLabel(equationFrame)
        self.xEquationLabel.setObjectName("xEquationLabel")
        self.gridLayout.addWidget(self.xEquationLabel, 9, 0, 1, 3)
        self.xEquationLabel_2 = QtWidgets.QLabel(equationFrame)
        self.xEquationLabel_2.setObjectName("xEquationLabel_2")
        self.gridLayout.addWidget(self.xEquationLabel_2, 9, 3, 1, 5)
        self.xTableView = EquationTableView(equationFrame)
        self.xTableView.setStyleSheet("QTableView { selection-background-color: palette(Highlight); }")
        self.xTableView.setAlternatingRowColors(True)
        self.xTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.xTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.xTableView.setObjectName("xTableView")
        self.xTableView.horizontalHeader().setStretchLastSection(True)
        self.xTableView.verticalHeader().setVisible(False)
        self.xTableView.verticalHeader().setHighlightSections(True)
        self.gridLayout.addWidget(self.xTableView, 10, 0, 1, 3)
        self.lineStyleComboBox = QtWidgets.QComboBox(equationFrame)
        self.lineStyleComboBox.setObjectName("lineStyleComboBox")
        self.gridLayout.addWidget(self.lineStyleComboBox, 15, 2, 1, 3)
        self.markerSizeSpinBox = QtWidgets.QSpinBox(equationFrame)
        self.markerSizeSpinBox.setMinimum(1)
        self.markerSizeSpinBox.setProperty("value", 2)
        self.markerSizeSpinBox.setObjectName("markerSizeSpinBox")
        self.gridLayout.addWidget(self.markerSizeSpinBox, 16, 6, 1, 2)
        self.xAxisComboBox = QtWidgets.QComboBox(equationFrame)
        self.xAxisComboBox.setObjectName("xAxisComboBox")
        self.xAxisComboBox.addItem("")
        self.xAxisComboBox.addItem("")
        self.gridLayout.addWidget(self.xAxisComboBox, 5, 7, 1, 1)
        self.xOriginLabel = QtWidgets.QLabel(equationFrame)
        self.xOriginLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xOriginLabel.setObjectName("xOriginLabel")
        self.gridLayout.addWidget(self.xOriginLabel, 5, 1, 1, 1)
        self.xOriginSpinBox = QtWidgets.QSpinBox(equationFrame)
        self.xOriginSpinBox.setMaximum(10)
        self.xOriginSpinBox.setObjectName("xOriginSpinBox")
        self.gridLayout.addWidget(self.xOriginSpinBox, 5, 2, 1, 1)
        self.xSpanLabel = QtWidgets.QLabel(equationFrame)
        self.xSpanLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xSpanLabel.setObjectName("xSpanLabel")
        self.gridLayout.addWidget(self.xSpanLabel, 5, 4, 1, 1)
        self.yAxisComboBox = QtWidgets.QComboBox(equationFrame)
        self.yAxisComboBox.setObjectName("yAxisComboBox")
        self.yAxisComboBox.addItem("")
        self.yAxisComboBox.addItem("")
        self.gridLayout.addWidget(self.yAxisComboBox, 6, 7, 1, 1)
        self.ySpanLabel = QtWidgets.QLabel(equationFrame)
        self.ySpanLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ySpanLabel.setObjectName("ySpanLabel")
        self.gridLayout.addWidget(self.ySpanLabel, 6, 4, 1, 1)
        self.yOriginSpinBox = QtWidgets.QSpinBox(equationFrame)
        self.yOriginSpinBox.setMaximum(10)
        self.yOriginSpinBox.setObjectName("yOriginSpinBox")
        self.gridLayout.addWidget(self.yOriginSpinBox, 6, 2, 1, 1)
        self.yOriginLabel = QtWidgets.QLabel(equationFrame)
        self.yOriginLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yOriginLabel.setObjectName("yOriginLabel")
        self.gridLayout.addWidget(self.yOriginLabel, 6, 1, 1, 1)
        self.ySpanSpinBox = QtWidgets.QSpinBox(equationFrame)
        self.ySpanSpinBox.setMinimum(1)
        self.ySpanSpinBox.setMaximum(10)
        self.ySpanSpinBox.setProperty("value", 1)
        self.ySpanSpinBox.setObjectName("ySpanSpinBox")
        self.gridLayout.addWidget(self.ySpanSpinBox, 6, 5, 1, 1)
        self.yAxisLabel = QtWidgets.QLabel(equationFrame)
        self.yAxisLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yAxisLabel.setObjectName("yAxisLabel")
        self.gridLayout.addWidget(self.yAxisLabel, 6, 6, 1, 1)
        self.xSpanSpinBox = QtWidgets.QSpinBox(equationFrame)
        self.xSpanSpinBox.setMinimum(1)
        self.xSpanSpinBox.setMaximum(10)
        self.xSpanSpinBox.setObjectName("xSpanSpinBox")
        self.gridLayout.addWidget(self.xSpanSpinBox, 5, 5, 1, 1)
        self.markerStyleComboBox = QtWidgets.QComboBox(equationFrame)
        self.markerStyleComboBox.setObjectName("markerStyleComboBox")
        self.gridLayout.addWidget(self.markerStyleComboBox, 16, 2, 1, 3)
        self.toolbarFrame = QtWidgets.QFrame(equationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbarFrame.sizePolicy().hasHeightForWidth())
        self.toolbarFrame.setSizePolicy(sizePolicy)
        self.toolbarFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.toolbarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolbarFrame.setObjectName("toolbarFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolbarFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.panToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/black/32/arrow_left_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.panToolButton.setIcon(icon)
        self.panToolButton.setIconSize(QtCore.QSize(24, 24))
        self.panToolButton.setCheckable(True)
        self.panToolButton.setChecked(False)
        self.panToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.panToolButton.setAutoRaise(True)
        self.panToolButton.setObjectName("panToolButton")
        self.horizontalLayout.addWidget(self.panToolButton)
        self.zoomToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG/black/32/zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomToolButton.setIcon(icon1)
        self.zoomToolButton.setIconSize(QtCore.QSize(24, 24))
        self.zoomToolButton.setCheckable(True)
        self.zoomToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.zoomToolButton.setAutoRaise(True)
        self.zoomToolButton.setObjectName("zoomToolButton")
        self.horizontalLayout.addWidget(self.zoomToolButton)
        self.homeToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/PNG/black/32/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeToolButton.setIcon(icon2)
        self.homeToolButton.setIconSize(QtCore.QSize(24, 24))
        self.homeToolButton.setCheckable(False)
        self.homeToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.homeToolButton.setAutoRaise(True)
        self.homeToolButton.setObjectName("homeToolButton")
        self.horizontalLayout.addWidget(self.homeToolButton)
        self.settingsToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/PNG/black/32/cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsToolButton.setIcon(icon3)
        self.settingsToolButton.setIconSize(QtCore.QSize(24, 24))
        self.settingsToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.settingsToolButton.setAutoRaise(True)
        self.settingsToolButton.setObjectName("settingsToolButton")
        self.horizontalLayout.addWidget(self.settingsToolButton)
        self.line_2 = QtWidgets.QFrame(self.toolbarFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.clearToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/PNG/black/32/cancel-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearToolButton.setIcon(icon4)
        self.clearToolButton.setIconSize(QtCore.QSize(24, 24))
        self.clearToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.clearToolButton.setAutoRaise(True)
        self.clearToolButton.setObjectName("clearToolButton")
        self.horizontalLayout.addWidget(self.clearToolButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.toolbarFrame, 0, 0, 1, 8)
        self.xAxisLabel = QtWidgets.QLabel(equationFrame)
        self.xAxisLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xAxisLabel.setObjectName("xAxisLabel")
        self.gridLayout.addWidget(self.xAxisLabel, 5, 6, 1, 1)
        self.yShareAxisCheckBox = QtWidgets.QCheckBox(equationFrame)
        self.yShareAxisCheckBox.setObjectName("yShareAxisCheckBox")
        self.gridLayout.addWidget(self.yShareAxisCheckBox, 6, 0, 1, 1)
        self.xShareAxisCheckBox = QtWidgets.QCheckBox(equationFrame)
        self.xShareAxisCheckBox.setObjectName("xShareAxisCheckBox")
        self.gridLayout.addWidget(self.xShareAxisCheckBox, 5, 0, 1, 1)
        self.selectAxesLabel.setBuddy(self.selectedAxesComboBox)
        self.titleLabel.setBuddy(self.axesTitleLineEdit)
        self.axesTitleLabel.setBuddy(self.axesComboBox)
        self.gridLabel.setBuddy(self.majorGridCheckBox)
        self.xStrLabel.setBuddy(self.xStrLineEdit)
        self.yStrLabel.setBuddy(self.yStrLineEdit)
        self.optionsLabel.setBuddy(self.optionsLineEdit)
        self.transformLabel.setBuddy(self.transformComboBox)
        self.xEquationLabel.setBuddy(self.xStrLineEdit)
        self.xEquationLabel_2.setBuddy(self.yStrLineEdit)
        self.xOriginLabel.setBuddy(self.xOriginSpinBox)
        self.xSpanLabel.setBuddy(self.xSpanSpinBox)
        self.ySpanLabel.setBuddy(self.ySpanSpinBox)
        self.yOriginLabel.setBuddy(self.yOriginSpinBox)
        self.yAxisLabel.setBuddy(self.yAxisComboBox)
        self.xAxisLabel.setBuddy(self.xAxisComboBox)

        self.retranslateUi(equationFrame)
        QtCore.QMetaObject.connectSlotsByName(equationFrame)
        equationFrame.setTabOrder(self.panToolButton, self.zoomToolButton)
        equationFrame.setTabOrder(self.zoomToolButton, self.homeToolButton)
        equationFrame.setTabOrder(self.homeToolButton, self.settingsToolButton)
        equationFrame.setTabOrder(self.settingsToolButton, self.clearToolButton)
        equationFrame.setTabOrder(self.clearToolButton, self.selectedAxesComboBox)
        equationFrame.setTabOrder(self.selectedAxesComboBox, self.axesComboBox)
        equationFrame.setTabOrder(self.axesComboBox, self.axesTitleLineEdit)
        equationFrame.setTabOrder(self.axesTitleLineEdit, self.xShareAxisCheckBox)
        equationFrame.setTabOrder(self.xShareAxisCheckBox, self.xOriginSpinBox)
        equationFrame.setTabOrder(self.xOriginSpinBox, self.xSpanSpinBox)
        equationFrame.setTabOrder(self.xSpanSpinBox, self.xAxisComboBox)
        equationFrame.setTabOrder(self.xAxisComboBox, self.yShareAxisCheckBox)
        equationFrame.setTabOrder(self.yShareAxisCheckBox, self.yOriginSpinBox)
        equationFrame.setTabOrder(self.yOriginSpinBox, self.ySpanSpinBox)
        equationFrame.setTabOrder(self.ySpanSpinBox, self.yAxisComboBox)
        equationFrame.setTabOrder(self.yAxisComboBox, self.transformComboBox)
        equationFrame.setTabOrder(self.transformComboBox, self.xTableView)
        equationFrame.setTabOrder(self.xTableView, self.yTableView)
        equationFrame.setTabOrder(self.yTableView, self.xStrLineEdit)
        equationFrame.setTabOrder(self.xStrLineEdit, self.xFormatComboBox)
        equationFrame.setTabOrder(self.xFormatComboBox, self.yStrLineEdit)
        equationFrame.setTabOrder(self.yStrLineEdit, self.yFormatComboBox)
        equationFrame.setTabOrder(self.yFormatComboBox, self.majorGridCheckBox)
        equationFrame.setTabOrder(self.majorGridCheckBox, self.minorGridCheckBox)
        equationFrame.setTabOrder(self.minorGridCheckBox, self.lineCheckBox)
        equationFrame.setTabOrder(self.lineCheckBox, self.lineStyleComboBox)
        equationFrame.setTabOrder(self.lineStyleComboBox, self.markerCheckBox)
        equationFrame.setTabOrder(self.markerCheckBox, self.markerSizeSpinBox)
        equationFrame.setTabOrder(self.markerSizeSpinBox, self.markerStyleComboBox)
        equationFrame.setTabOrder(self.markerStyleComboBox, self.optionsLineEdit)
        equationFrame.setTabOrder(self.optionsLineEdit, self.plotPushButton)

    def retranslateUi(self, equationFrame):
        equationFrame.setWindowTitle(QtWidgets.QApplication.translate("equationFrame", "Frame", None, -1))
        self.selectAxesLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Select Axes:", None, -1))
        self.titleLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Axes Title:", None, -1))
        self.selectedAxesComboBox.setItemText(0, QtWidgets.QApplication.translate("equationFrame", "< New Axes >", None, -1))
        self.axesTitleLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Axes Type:", None, -1))
        self.axesComboBox.setItemText(0, QtWidgets.QApplication.translate("equationFrame", "Rectangular", None, -1))
        self.axesComboBox.setItemText(1, QtWidgets.QApplication.translate("equationFrame", "Polar", None, -1))
        self.axesComboBox.setItemText(2, QtWidgets.QApplication.translate("equationFrame", "Smith", None, -1))
        self.majorGridCheckBox.setText(QtWidgets.QApplication.translate("equationFrame", "Major", None, -1))
        self.minorGridCheckBox.setText(QtWidgets.QApplication.translate("equationFrame", "Minor", None, -1))
        self.gridLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Axes Grid:", None, -1))
        self.selectedPlotLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Select Plot:", None, -1))
        self.plotLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Plot Type:", None, -1))
        self.xStrLabel.setText(QtWidgets.QApplication.translate("equationFrame", "X Label", None, -1))
        self.xFormatComboBox.setItemText(0, QtWidgets.QApplication.translate("equationFrame", "Lin Mag", None, -1))
        self.xFormatComboBox.setItemText(1, QtWidgets.QApplication.translate("equationFrame", "dBm", None, -1))
        self.xFormatComboBox.setItemText(2, QtWidgets.QApplication.translate("equationFrame", "dB", None, -1))
        self.xFormatComboBox.setItemText(3, QtWidgets.QApplication.translate("equationFrame", "Re", None, -1))
        self.xFormatComboBox.setItemText(4, QtWidgets.QApplication.translate("equationFrame", "Im", None, -1))
        self.xFormatComboBox.setItemText(5, QtWidgets.QApplication.translate("equationFrame", "Angle Deg", None, -1))
        self.xFormatComboBox.setItemText(6, QtWidgets.QApplication.translate("equationFrame", "Angle Rad", None, -1))
        self.yFormatComboBox.setItemText(0, QtWidgets.QApplication.translate("equationFrame", "Lin Mag", None, -1))
        self.yFormatComboBox.setItemText(1, QtWidgets.QApplication.translate("equationFrame", "dBm", None, -1))
        self.yFormatComboBox.setItemText(2, QtWidgets.QApplication.translate("equationFrame", "dB", None, -1))
        self.yFormatComboBox.setItemText(3, QtWidgets.QApplication.translate("equationFrame", "Re", None, -1))
        self.yFormatComboBox.setItemText(4, QtWidgets.QApplication.translate("equationFrame", "Im", None, -1))
        self.yFormatComboBox.setItemText(5, QtWidgets.QApplication.translate("equationFrame", "Angle Deg", None, -1))
        self.yFormatComboBox.setItemText(6, QtWidgets.QApplication.translate("equationFrame", "Angle Rad", None, -1))
        self.yStrLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Y Label:", None, -1))
        self.lineStyleLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Style:", None, -1))
        self.lineCheckBox.setText(QtWidgets.QApplication.translate("equationFrame", "Line:", None, -1))
        self.lineSizeLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Size:", None, -1))
        self.markerCheckBox.setText(QtWidgets.QApplication.translate("equationFrame", "Marker:", None, -1))
        self.markerSizeLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Size:", None, -1))
        self.markerStyleLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Style:", None, -1))
        self.optionsLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Options:", None, -1))
        self.plotPushButton.setText(QtWidgets.QApplication.translate("equationFrame", "Create New Plot", None, -1))
        self.plotPushButton.setShortcut(QtWidgets.QApplication.translate("equationFrame", "Ctrl+Return", None, -1))
        self.transformLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Transform:", None, -1))
        self.xEquationLabel.setText(QtWidgets.QApplication.translate("equationFrame", "X:", None, -1))
        self.xEquationLabel_2.setText(QtWidgets.QApplication.translate("equationFrame", "Y:", None, -1))
        self.xAxisComboBox.setItemText(0, QtWidgets.QApplication.translate("equationFrame", "linear", None, -1))
        self.xAxisComboBox.setItemText(1, QtWidgets.QApplication.translate("equationFrame", "log", None, -1))
        self.xOriginLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Origin:", None, -1))
        self.xSpanLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Span:", None, -1))
        self.yAxisComboBox.setItemText(0, QtWidgets.QApplication.translate("equationFrame", "linear", None, -1))
        self.yAxisComboBox.setItemText(1, QtWidgets.QApplication.translate("equationFrame", "log", None, -1))
        self.ySpanLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Span:", None, -1))
        self.yOriginLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Origin:", None, -1))
        self.yAxisLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Axis:", None, -1))
        self.panToolButton.setToolTip(QtWidgets.QApplication.translate("equationFrame", "Pan left-mouse, Zoom right-mouse", None, -1))
        self.panToolButton.setText(QtWidgets.QApplication.translate("equationFrame", "Pan", None, -1))
        self.zoomToolButton.setToolTip(QtWidgets.QApplication.translate("equationFrame", "Zoom to A", None, -1))
        self.zoomToolButton.setText(QtWidgets.QApplication.translate("equationFrame", "Zoom", None, -1))
        self.homeToolButton.setToolTip(QtWidgets.QApplication.translate("equationFrame", "Auto-Scale", None, -1))
        self.homeToolButton.setText(QtWidgets.QApplication.translate("equationFrame", "Home", None, -1))
        self.settingsToolButton.setToolTip(QtWidgets.QApplication.translate("equationFrame", "Settings", None, -1))
        self.settingsToolButton.setText(QtWidgets.QApplication.translate("equationFrame", "Settings", None, -1))
        self.clearToolButton.setToolTip(QtWidgets.QApplication.translate("equationFrame", "Clear", None, -1))
        self.clearToolButton.setText(QtWidgets.QApplication.translate("equationFrame", "Clear", None, -1))
        self.xAxisLabel.setText(QtWidgets.QApplication.translate("equationFrame", "Axis:", None, -1))
        self.yShareAxisCheckBox.setText(QtWidgets.QApplication.translate("equationFrame", "Share Y Axis:", None, -1))
        self.xShareAxisCheckBox.setText(QtWidgets.QApplication.translate("equationFrame", "Share X Axis:", None, -1))

from sknrf.app.dataviewer.view.equation.widget import EquationTableView
