# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QImageFrame.ui',
# licensing of 'QImageFrame.ui' applies.
#
# Created: Sat Jan 19 23:21:32 2019
#      by: pyside2-uic  running on PySide2 5.12.1a1
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_imageFrame(object):
    def setupUi(self, imageFrame):
        imageFrame.setObjectName("imageFrame")
        imageFrame.resize(463, 719)
        imageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        imageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.formLayout = QtWidgets.QFormLayout(imageFrame)
        self.formLayout.setObjectName("formLayout")
        self.toolbarFrame = QtWidgets.QFrame(imageFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbarFrame.sizePolicy().hasHeightForWidth())
        self.toolbarFrame.setSizePolicy(sizePolicy)
        self.toolbarFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.toolbarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolbarFrame.setObjectName("toolbarFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.toolbarFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exportToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/black/32/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportToolButton.setIcon(icon)
        self.exportToolButton.setIconSize(QtCore.QSize(24, 24))
        self.exportToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.exportToolButton.setAutoRaise(True)
        self.exportToolButton.setObjectName("exportToolButton")
        self.horizontalLayout_2.addWidget(self.exportToolButton)
        self.line = QtWidgets.QFrame(self.toolbarFrame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.zoomToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG/black/32/zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomToolButton.setIcon(icon1)
        self.zoomToolButton.setIconSize(QtCore.QSize(24, 24))
        self.zoomToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.zoomToolButton.setAutoRaise(True)
        self.zoomToolButton.setObjectName("zoomToolButton")
        self.horizontalLayout_2.addWidget(self.zoomToolButton)
        self.homeToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/PNG/black/32/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeToolButton.setIcon(icon2)
        self.homeToolButton.setIconSize(QtCore.QSize(24, 24))
        self.homeToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.homeToolButton.setAutoRaise(True)
        self.homeToolButton.setObjectName("homeToolButton")
        self.horizontalLayout_2.addWidget(self.homeToolButton)
        self.sliceToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/PNG/black/32/pen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sliceToolButton.setIcon(icon3)
        self.sliceToolButton.setIconSize(QtCore.QSize(24, 24))
        self.sliceToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.sliceToolButton.setAutoRaise(True)
        self.sliceToolButton.setObjectName("sliceToolButton")
        self.horizontalLayout_2.addWidget(self.sliceToolButton)
        self.subplotsToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/PNG/black/32/equalizer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subplotsToolButton.setIcon(icon4)
        self.subplotsToolButton.setIconSize(QtCore.QSize(24, 24))
        self.subplotsToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.subplotsToolButton.setAutoRaise(True)
        self.subplotsToolButton.setObjectName("subplotsToolButton")
        self.horizontalLayout_2.addWidget(self.subplotsToolButton)
        self.line_3 = QtWidgets.QFrame(self.toolbarFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.trackingToolButton = QtWidgets.QToolButton(self.toolbarFrame)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/PNG/black/32/target.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trackingToolButton.setIcon(icon5)
        self.trackingToolButton.setIconSize(QtCore.QSize(24, 24))
        self.trackingToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.trackingToolButton.setAutoRaise(True)
        self.trackingToolButton.setObjectName("trackingToolButton")
        self.horizontalLayout_2.addWidget(self.trackingToolButton)
        self.coordinatesComboBox = QtWidgets.QComboBox(self.toolbarFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordinatesComboBox.sizePolicy().hasHeightForWidth())
        self.coordinatesComboBox.setSizePolicy(sizePolicy)
        self.coordinatesComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.coordinatesComboBox.setObjectName("coordinatesComboBox")
        self.coordinatesComboBox.addItem("")
        self.coordinatesComboBox.addItem("")
        self.coordinatesComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.coordinatesComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.toolbarFrame)
        self.videoLabel = QtWidgets.QLabel(imageFrame)
        self.videoLabel.setObjectName("videoLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.videoLabel)
        self.videoComboBox = QtWidgets.QComboBox(imageFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoComboBox.sizePolicy().hasHeightForWidth())
        self.videoComboBox.setSizePolicy(sizePolicy)
        self.videoComboBox.setObjectName("videoComboBox")
        self.videoComboBox.addItem("")
        self.videoComboBox.addItem("")
        self.videoComboBox.addItem("")
        self.videoComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.videoComboBox)
        self.colormapLabel = QtWidgets.QLabel(imageFrame)
        self.colormapLabel.setObjectName("colormapLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.colormapLabel)
        self.colormapComboBox = QtWidgets.QComboBox(imageFrame)
        self.colormapComboBox.setObjectName("colormapComboBox")
        self.colormapComboBox.addItem("")
        self.colormapComboBox.addItem("")
        self.colormapComboBox.addItem("")
        self.colormapComboBox.addItem("")
        self.colormapComboBox.addItem("")
        self.colormapComboBox.addItem("")
        self.colormapComboBox.addItem("")
        self.colormapComboBox.addItem("")
        self.colormapComboBox.addItem("")
        self.colormapComboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.colormapComboBox)
        self.showLabel = QtWidgets.QLabel(imageFrame)
        self.showLabel.setObjectName("showLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.showLabel)
        self.showComboBox = QtWidgets.QComboBox(imageFrame)
        self.showComboBox.setObjectName("showComboBox")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/PNG/black/32/videocamera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showComboBox.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/PNG/black/32/stats-dots.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showComboBox.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/PNG/black/32/stats-bars.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showComboBox.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/PNG/black/32/table2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showComboBox.addItem(icon9, "")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.showComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.exportFrame = QtWidgets.QFrame(imageFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportFrame.sizePolicy().hasHeightForWidth())
        self.exportFrame.setSizePolicy(sizePolicy)
        self.exportFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exportFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exportFrame.setObjectName("exportFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.exportFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contentFigure = QtWidgets.QFrame(self.exportFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentFigure.sizePolicy().hasHeightForWidth())
        self.contentFigure.setSizePolicy(sizePolicy)
        self.contentFigure.setAutoFillBackground(False)
        self.contentFigure.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentFigure.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentFigure.setObjectName("contentFigure")
        self.verticalLayout.addWidget(self.contentFigure)
        self.coordinatesLabel = QtWidgets.QLabel(self.exportFrame)
        self.coordinatesLabel.setObjectName("coordinatesLabel")
        self.verticalLayout.addWidget(self.coordinatesLabel)
        self.metadataTextEdit = QtWidgets.QPlainTextEdit(self.exportFrame)
        self.metadataTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadataTextEdit.sizePolicy().hasHeightForWidth())
        self.metadataTextEdit.setSizePolicy(sizePolicy)
        self.metadataTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.metadataTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.metadataTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.metadataTextEdit.setReadOnly(True)
        self.metadataTextEdit.setObjectName("metadataTextEdit")
        self.verticalLayout.addWidget(self.metadataTextEdit)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.exportFrame)
        self.videoLabel.setBuddy(self.videoComboBox)
        self.colormapLabel.setBuddy(self.colormapComboBox)
        self.showLabel.setBuddy(self.showComboBox)

        self.retranslateUi(imageFrame)
        self.videoComboBox.setCurrentIndex(3)
        self.colormapComboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(imageFrame)

    def retranslateUi(self, imageFrame):
        imageFrame.setWindowTitle(QtWidgets.QApplication.translate("imageFrame", "Frame", None, -1))
        self.exportToolButton.setText(QtWidgets.QApplication.translate("imageFrame", "Export", None, -1))
        self.exportToolButton.setShortcut(QtWidgets.QApplication.translate("imageFrame", "Enter", None, -1))
        self.zoomToolButton.setText(QtWidgets.QApplication.translate("imageFrame", "Zoom", None, -1))
        self.homeToolButton.setText(QtWidgets.QApplication.translate("imageFrame", "Home", None, -1))
        self.sliceToolButton.setText(QtWidgets.QApplication.translate("imageFrame", "Slice", None, -1))
        self.subplotsToolButton.setText(QtWidgets.QApplication.translate("imageFrame", "Subplots", None, -1))
        self.trackingToolButton.setToolTip(QtWidgets.QApplication.translate("imageFrame", "Hover/Click Toggle", None, -1))
        self.trackingToolButton.setText(QtWidgets.QApplication.translate("imageFrame", "Tracking", None, -1))
        self.coordinatesComboBox.setItemText(0, QtWidgets.QApplication.translate("imageFrame", "RI", None, -1))
        self.coordinatesComboBox.setItemText(1, QtWidgets.QApplication.translate("imageFrame", "MA", None, -1))
        self.coordinatesComboBox.setItemText(2, QtWidgets.QApplication.translate("imageFrame", "Z", None, -1))
        self.videoLabel.setText(QtWidgets.QApplication.translate("imageFrame", "Video:", None, -1))
        self.videoComboBox.setItemText(0, QtWidgets.QApplication.translate("imageFrame", "Visible", None, -1))
        self.videoComboBox.setItemText(1, QtWidgets.QApplication.translate("imageFrame", "SWIR", None, -1))
        self.videoComboBox.setItemText(2, QtWidgets.QApplication.translate("imageFrame", "LWIR", None, -1))
        self.videoComboBox.setItemText(3, QtWidgets.QApplication.translate("imageFrame", "MWIR", None, -1))
        self.colormapLabel.setText(QtWidgets.QApplication.translate("imageFrame", "Color Map:", None, -1))
        self.colormapComboBox.setItemText(0, QtWidgets.QApplication.translate("imageFrame", "gray", None, -1))
        self.colormapComboBox.setItemText(1, QtWidgets.QApplication.translate("imageFrame", "gray_log", None, -1))
        self.colormapComboBox.setItemText(2, QtWidgets.QApplication.translate("imageFrame", "qfi", None, -1))
        self.colormapComboBox.setItemText(3, QtWidgets.QApplication.translate("imageFrame", "qfi_log", None, -1))
        self.colormapComboBox.setItemText(4, QtWidgets.QApplication.translate("imageFrame", "plasma", None, -1))
        self.colormapComboBox.setItemText(5, QtWidgets.QApplication.translate("imageFrame", "viridis", None, -1))
        self.colormapComboBox.setItemText(6, QtWidgets.QApplication.translate("imageFrame", "tab10", None, -1))
        self.colormapComboBox.setItemText(7, QtWidgets.QApplication.translate("imageFrame", "tab20", None, -1))
        self.colormapComboBox.setItemText(8, QtWidgets.QApplication.translate("imageFrame", "spectral", None, -1))
        self.colormapComboBox.setItemText(9, QtWidgets.QApplication.translate("imageFrame", "bwr", None, -1))
        self.showLabel.setText(QtWidgets.QApplication.translate("imageFrame", "Show:", None, -1))
        self.showComboBox.setItemText(0, QtWidgets.QApplication.translate("imageFrame", "Image", None, -1))
        self.showComboBox.setItemText(1, QtWidgets.QApplication.translate("imageFrame", "Slice", None, -1))
        self.showComboBox.setItemText(2, QtWidgets.QApplication.translate("imageFrame", "Histogram", None, -1))
        self.showComboBox.setItemText(3, QtWidgets.QApplication.translate("imageFrame", "Correlation Matrix", None, -1))
        self.coordinatesLabel.setText(QtWidgets.QApplication.translate("imageFrame", "<cursor>", None, -1))
        self.metadataTextEdit.setPlainText(QtWidgets.QApplication.translate("imageFrame", "<metadata>", None, -1))

