# Generated by Django 3.2.6 on 2022-02-14 14:13


# Disclaimer
# ----------
#
# Copyright (C) 2022 Helmholtz-Zentrum Hereon
#
# This file is part of django-helmholtz-aai and is released under the
# EUPL-1.2 license.
# See LICENSE in the root of the repository for full licensing details.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the EUROPEAN UNION PUBLIC LICENCE v. 1.2 or later
# as published by the European Commission.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# EUPL-1.2 license for more details.
#
# You should have received a copy of the EUPL-1.2 license along with this
# program. If not, see https://www.eupl.eu/.


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_helmholtz_aai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helmholtzuser",
            name="eduperson_unique_id",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="helmholtzvirtualorganization",
            name="eduperson_entitlement",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
