# Generated by Django 3.1.13 on 2021-11-24 20:38

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("los_docusign", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="docusignchoiceconfig",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="docusignchoiceconfig",
            name="is_removed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="docusignchoiceconfig",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="docusignenvelopeauditlog",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="docusignenvelopeauditlog",
            name="is_removed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="docusignenvelopeauditlog",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="docusignenvelopestagedata",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="docusignenvelopestagedata",
            name="is_removed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="docusignenvelopestagedata",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="docusignorgtemplate",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="docusignorgtemplate",
            name="is_removed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="docusignorgtemplate",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="docusignorgtemplateconfig",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="docusignorgtemplateconfig",
            name="is_removed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="docusignorgtemplateconfig",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="docusigntemplate",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="docusigntemplate",
            name="is_removed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="docusigntemplate",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="docusigntemplateorgexclusion",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="docusigntemplateorgexclusion",
            name="is_removed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="docusigntemplateorgexclusion",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="docusignuserauth",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="docusignuserauth",
            name="is_removed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="docusignuserauth",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterModelTable(
            name="docusigntemplateorgexclusion",
            table="docusign_template_org_exclusions",
        ),
    ]
