# Generated by Django 3.2.9 on 2022-01-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("los_docusign", "0003_auto_20211227_1445"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="docusignenvelopestagedata",
            name="unique_phase_content_type",
        ),
        migrations.AddConstraint(
            model_name="docusignenvelopestagedata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_removed", False)),
                fields=("object_pk", "content_type", "phase"),
                name="unique_phase_content_type",
            ),
        ),
    ]
