# Generated by Django 3.2.12 on 2022-03-03 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("los_docusign", "0005_docusignenvelopeauditlog_recipient_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docusignuserauth",
            name="two_factor_enabled_flag",
        ),
    ]
