# Generated by Django 3.1.13 on 2022-01-29 00:23

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("los_docusign", "0004_auto_20220119_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="docusignenvelopeauditlog",
            name="recipient_details",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
