# Generated by Django 3.2.16 on 2023-01-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("los_docusign", "0006_remove_docusignuserauth_two_factor_enabled_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docusignenvelopestagedata",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="Error Message"),
        ),
    ]
