# Generated by Django 3.2.16 on 2023-04-12 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("los_docusign", "0007_alter_docusignenvelopestagedata_error_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docusignenvelopeauditlog",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="docusignenvelopestagedata",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="docusignorgtemplate",
            name="docusign_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="los_docusign.docusigntemplate",
            ),
        ),
        migrations.AlterField(
            model_name="docusignorgtemplate",
            name="organization_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Organization Model",
            ),
        ),
        migrations.AlterField(
            model_name="docusignorgtemplateconfig",
            name="organization_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="docusignorgtemplateconfig",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="los_docusign.docusigntemplate",
            ),
        ),
        migrations.AlterField(
            model_name="docusigntemplate",
            name="template_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="los_docusign.docusignchoiceconfig",
            ),
        ),
        migrations.AlterField(
            model_name="docusigntemplateorgexclusion",
            name="document_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="los_docusign.docusignchoiceconfig",
            ),
        ),
        migrations.AlterField(
            model_name="docusigntemplateorgexclusion",
            name="organization_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Organization Model",
            ),
        ),
        migrations.AlterField(
            model_name="docusigntemplateorgexclusion",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="los_docusign.docusigntemplate",
            ),
        ),
        migrations.AlterField(
            model_name="docusignuserauth",
            name="organization_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Organization Model",
            ),
        ),
    ]
