ENCRYPT = 'ENCRYPT'
DECRYPT = 'DECRYPT'
ENCRYPT_WITH_DATA_KEY = 'ENCRYPT_WITH_DATA_KEY'
ENCRYPT_WITH_DATA_KEY_PAIR = 'ENCRYPT_WITH_DATA_KEY_PAIR'
DECRYPT_WITH_DATA_KEY = 'DECRYPT_WITH_DATA_KEY'
DECRYPT_WITH_DATA_KEY_PAIR = 'DECRYPT_WITH_DATA_KEY_PAIR'

DELETE_KEY = 'DELETE_KEY'
DISABLE_KEY = 'DISABLE_KEY'
ENABLE_KEY = 'ENABLE_KEY'

UPDATE_ALIAS = 'UPDATE_ALIAS'
DELETE_ALIAS = 'DELETE_ALIAS'

GENERATE_DATA_KEY = 'GENERATE_DATA_KEY'
GENERATE_DATA_KEY_PAIR = 'GENERATE_DATA_KEY_PAIR'

UPDATE_DESCRIPTION_KEY = 'UPDATE_DESCRIPTION_KEY'

DESCRIBE_KEY = 'DESCRIBE_KEY'

SIGN = 'SIGN'
VERIFY = 'VERIFY'