# -*- coding: utf-8 -*-

"""
swaggerpetstore

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class BeneficiaryBankAccountListItem(object):

    """Implementation of the 'BeneficiaryBankAccountListItem' model.

    This is used to populate a beneficiary bank account field which needs to
    be displayed as a list in the UI.

    Attributes:
        label (string): The visible label to be presented in the UI list.
        value (string): The stored value for the visible list item label.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "label": 'label',
        "value": 'value'
    }

    def __init__(self,
                 label=None,
                 value=None):
        """Constructor for the BeneficiaryBankAccountListItem class"""

        # Initialize members of the class
        self.label = label 
        self.value = value 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        label = dictionary.get("label") if dictionary.get("label") else None
        value = dictionary.get("value") if dictionary.get("value") else None
        # Return an object of this model
        return cls(label,
                   value)
