# -*- coding: utf-8 -*-

"""
swaggerpetstore

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Failure(object):

    """Implementation of the 'Failure' model.

    An individual failure/error description. This is used by the
    ValidationException model.

    Attributes:
        key (string): Key identifies the specific field which is in error.
        code (long|int): Earthport specific validation error code.
        value (string): Descriptive explanation of the error.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "key": 'key',
        "code": 'code',
        "value": 'value'
    }

    def __init__(self,
                 key=None,
                 code=None,
                 value=None):
        """Constructor for the Failure class"""

        # Initialize members of the class
        self.key = key 
        self.code = code 
        self.value = value 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        key = dictionary.get("key") if dictionary.get("key") else None
        code = dictionary.get("code") if dictionary.get("code") else None
        value = dictionary.get("value") if dictionary.get("value") else None
        # Return an object of this model
        return cls(key,
                   code,
                   value)
