# -*- coding: utf-8 -*-

"""
swaggerpetstore

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ServiceLevelEnum(object):

    """Implementation of the 'ServiceLevel' enum.

    Supported service levels for a payout request (standard or express).

    Attributes:
        STANDARD: Standard service level payments.
        EXPRESS: Express service level payments.

    """

    STANDARD = 'standard'

    EXPRESS = 'express'
